### ISSUE TITLE
Final cleanup of code before version 1.0

### ISSUE THREAD

**Issue by m-aguena** [LSSTDESC/CLMM#372] opened 2021-02-12 15:13 UTC
Make a final cleanup of the code before tagging it v1.0.
We should choose one formatting ([pep8](pep8.org) maybe) and make sure the code conforms to it.

Also, minor fixes:
- [x] `GCData.__getitem__` has some unecessary internal computations and could be simplified
- [x] Fix formatting of docstring for `z_src_model` in `clmm/theory/func_layer.py`
- [x] Fix equation of Sigma in documentation to `\int \rho`

**Comment by cristobal-sifon** [comment] 2021-06-02 14:07
do we also want to add a `src` folder to contain `clmm`? I can't see any 'official' stance on this but I've become convinced it is good practice. Here's a discussion on why that is the case: https://blog.ionelmc.ro/2014/05/25/python-packaging/

**Comment by johannct** [comment] 2021-06-05 10:30
The link provided is from 2014, so even the pitfalls described there may not be up to date. I think most current packages. I am more familiar with the practice that in `src` (or `bin.src` in DM projects) are put things that either need compilation or are meant to end up in a `bin` directory so that they are executable scripts or binaries. I would propose to close this issue and bump up the question to #desc-compconveners and #desc-pipelines.

**Comment by cristobal-sifon** [comment] 2021-06-05 12:58
That's fair, we can skip the `src` folder, but note that the issue is about a different suggestion, so I am OK with leaving my suggestion out but (IMO) we do need to follow @m-aguena's original one

**Closed** 2021-07-22 06:02 UTC
Labels: good first issue, priority
