### ISSUE TITLE
Preliminary infrastructure

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#1] opened 2018-06-01 17:43 UTC
We need documentation and continuous integration ahead of the workshop.  This requires a hello world jupyter notebook, a .travis.yml and setup.py, and autodoc/Sphinx set up.

**Comment by aimalz** [comment] 2018-07-27 17:32
@matthewkirby is setting up Travis.  @aimalz is setting up Sphinx.

**Comment by matthewkirby** [comment] 2018-07-28 03:18
I want to open a PR for branch . The problem is that I merged it with issue/4/galaxycluster_outline so that there were docstrings to test against. Is the fix for this just to delete the galaxycluster.py I merged with and PR into master?

**Comment by matthewkirby** [comment] 2018-07-28 03:19
Whoops, the branch is testadddocstring. Sorry for the name =X it preceeded the explanation of branch names

**Comment by msimet** [comment] 2018-07-28 08:35
No, don't delete the file. The problem is that git would know that the
delete-file commit came after the commits that added the file, so it could
do funny things when you try to merge the other branch later. I would
suggest one of two options:

1. Just make the PR as is, but don't have anyone review or merge it until
the branch you merged in has gone through PR.
2. Use git log or https://github.com/LSSTDESC/CLMM/commits/testadddocstring
to find and copy the SHAs for all of the commits you made to this branch.
Then, make a new branch from master and 'git cherry-pick' all of the
commits onto the new branch in order, and do a PR from there.

There are probably other solutions too, but those are the two easiest I can
come up with off the top of my head!

**Comment by matthewkirby** [comment] 2018-07-28 19:46
Thanks for the suggestions. I issued a PR for the read the docs files.

**Comment by cavestruz** [comment] 2018-07-29 15:12
- Need automatically build the readthedocs
- Need to fix class documentation Issue #15

**Comment by matthewkirby** [comment] 2018-07-30 04:54
Things that still need to be done before this can be closed

- [ ] Readthedocs
    - [ ] Autoapi needs to be run automatically rather than manually.
- [ ] Travis-ci
- [ ] License (Issue #28)

**Closed** 2018-07-31 14:08 UTC
Labels: priority
