### ISSUE TITLE
Initial data reduction

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/CLMM#10] opened 2018-07-28 15:33 UTC
We need to turn the observed data of #9 into azimuthal averages.  For now, let's have an AzimuthalAverager subclass of a DataSummarizer/DataReducer superclass that 

1. takes a GalaxyCluster and bin definitions
2. Uses the GalaxyCluster's redshift, center, and galaxy positions to subdivide galaxies into bins
3. Performs the azimuthal averaging
4. Has the GalaxyCluster add the RadialProfile data output to its data

**Comment by cavestruz** [comment] 2018-07-29 15:05
Duplicate of Issue #3

**Closed** 2018-07-29 15:05 UTC
